
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author AGAMUYI PRECIOUS
 */
public class Corp_Admin_Update extends javax.swing.JFrame {

    /**
     * Creates new form Corp_Admin_Update
     */
    public Corp_Admin_Update() {
        super("Corp_Admin_Update");
        initComponents();
        
    }
    
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    
    

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        word = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        mail = new javax.swing.JTextField();
        view = new javax.swing.JTextField();
        src = new javax.swing.JButton();
        date = new javax.swing.JButton();
        rst = new javax.swing.JButton();
        bak = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("UserName:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 60, 90, 20);
        jPanel1.add(name);
        name.setBounds(120, 60, 170, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 153));
        jLabel2.setText("Password:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 130, 80, 17);
        jPanel1.add(word);
        word.setBounds(120, 120, 170, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 153));
        jLabel3.setText("E-mail:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 190, 50, 17);
        jPanel1.add(mail);
        mail.setBounds(120, 180, 170, 30);
        jPanel1.add(view);
        view.setBounds(280, 20, 130, 30);

        src.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        src.setForeground(new java.awt.Color(153, 0, 153));
        src.setIcon(new javax.swing.ImageIcon("C:\\Users\\AGAMUYI PRECIOUS\\Documents\\NetBeansProjects\\NYSC CORPS_MEMBER REGISTRATION  SYSTEM\\my icons\\Search_50px.png")); // NOI18N
        src.setText("Search");
        src.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srcActionPerformed(evt);
            }
        });
        jPanel1.add(src);
        src.setBounds(430, 10, 140, 60);

        date.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        date.setForeground(new java.awt.Color(153, 0, 153));
        date.setIcon(new javax.swing.ImageIcon("C:\\Users\\AGAMUYI PRECIOUS\\Documents\\NetBeansProjects\\NYSC CORPS_MEMBER REGISTRATION  SYSTEM\\my icons\\Update_50px.png")); // NOI18N
        date.setText("Update");
        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });
        jPanel1.add(date);
        date.setBounds(70, 230, 139, 59);

        rst.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rst.setForeground(new java.awt.Color(153, 0, 153));
        rst.setIcon(new javax.swing.ImageIcon("C:\\Users\\AGAMUYI PRECIOUS\\Documents\\NetBeansProjects\\NYSC CORPS_MEMBER REGISTRATION  SYSTEM\\my icons\\Reset_50px.png")); // NOI18N
        rst.setText("Reset");
        rst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rstActionPerformed(evt);
            }
        });
        jPanel1.add(rst);
        rst.setBounds(240, 230, 127, 59);

        bak.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bak.setForeground(new java.awt.Color(153, 0, 153));
        bak.setIcon(new javax.swing.ImageIcon("C:\\Users\\AGAMUYI PRECIOUS\\Documents\\NetBeansProjects\\NYSC CORPS_MEMBER REGISTRATION  SYSTEM\\my icons\\Back Arrow_50px.png")); // NOI18N
        bak.setText("Back");
        bak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bakActionPerformed(evt);
            }
        });
        jPanel1.add(bak);
        bak.setBounds(390, 230, 121, 60);

        Delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Delete.setForeground(new java.awt.Color(153, 0, 102));
        Delete.setIcon(new javax.swing.ImageIcon("C:\\Users\\AGAMUYI PRECIOUS\\Documents\\NetBeansProjects\\NYSC CORPS_MEMBER REGISTRATION  SYSTEM\\my icons\\Delete_50px.png")); // NOI18N
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        jPanel1.add(Delete);
        Delete.setBounds(440, 140, 131, 60);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\AGAMUYI PRECIOUS\\Documents\\NetBeansProjects\\NYSC CORPS_MEMBER REGISTRATION  SYSTEM\\pix1.jpg")); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 580, 310);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rstActionPerformed
        // TODO add your handling code here:
        name.setText(null);
        word.setText(null);
        mail.setText(null);
        view.setText(null);
               
        
    }//GEN-LAST:event_rstActionPerformed

    private void bakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bakActionPerformed
        // TODO add your handling code here:
        setVisible(false);
      Home info = new Home();
      info.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_bakActionPerformed

    private void srcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srcActionPerformed
        // TODO add your handling code here:
                                              if(view.getText().equals("")){
                                                JOptionPane.showMessageDialog(null,"Please input your details \n the fields are empty"); 
                                               
        }else{
                                                  try{
                                                      
                                                    Nysc_Connect.getConnection();
                                                        conn = DriverManager.getConnection("jdbc:mysql://localhost/nysc resgistration system","root","");
                                                        String   sql =  "SELECT  *FROM admin where id = ?";
                                                        pst = conn.prepareStatement(sql);
                                                        pst.setString(1,view.getText());
                                                        rs =pst.executeQuery();
                                                        if(rs.next()){
                                                            
                                                            String rex1 = rs.getString("user_name");
                                                            name.setText(rex1);
                                                            String rex2 = rs.getString("password");
                                                            word.setText(rex2);
                                                            String rex3 = rs.getString("e_mail");
                                                            mail.setText(rex3);
                                                            rs.close();
                                                            pst.close();
                                                            
                                                                    
                                                        }else{
                                                            JOptionPane.showMessageDialog(null," No record of Corp Admin Found");
                                                        }      
                                                                    
                                                       
                                                  }catch(Exception e){
                                                      JOptionPane.showMessageDialog(null, e);
                                                  }
            
            
            
            
            
            
            
            
        }
    }//GEN-LAST:event_srcActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:\
                                                try{
                                                   String sql = "DELETE  from  admin WHERE id = ?";
                                                   pst = conn.prepareStatement(sql);
                                                   pst.setString(1, view.getText());
                                                   pst.executeUpdate();
                                                   setVisible(false);
                                                   Corp_Admin_View info = new Corp_Admin_View();
                                                   info.setVisible(true);
                                                   this.dispose();
                                                   
                           
                                                    
                                                    
                                                }catch(Exception e){
                                                    
                                                  JOptionPane.showMessageDialog(null, e);
                                                }
                                                    
    }//GEN-LAST:event_DeleteActionPerformed

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
                                                      if(name.getText().equals("")){
                                                          
                                                JOptionPane.showMessageDialog(null,"Please input your details \n the fields are empty");
                                                }else{
                                                          
                                                try{
                                                    
                                                   String value1  = name.getText();
                                                   String value2  = word.getText();
                                                   String value3  = mail.getText();
                                                   String value4 = view.getText();
                                                    
                                                Nysc_Connect.getConnection();
                                                String  sql ="UPDATE admin SET user_name ='"+value1+"',password ='"+value2+"', e_mail ='"+value3+"' WHERE id ='"+value4+"'";
                                                  conn =DriverManager.getConnection("jdbc:mysql://localhost/nysc resgistration system","root","");
                                                  pst = conn.prepareStatement(sql);
                                                  pst.execute();
                                                  
                                                  JOptionPane.showMessageDialog(null, "Corp Admin details successfully Update");
                                               
                                                            
                                                              
                                                          }catch(Exception e){
                                                              
                                                              JOptionPane.showMessageDialog(null, e);
                                                          }
                                                          
                                                         
                                                          
                                                      }
                                                      
                                                      
                                                      
    }//GEN-LAST:event_dateActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
 ImageIcon image = new ImageIcon("C:\\Users\\AGAMUYI PRECIOUS\\Documents\\NetBeansProjects\\NYSC CORPS_MEMBER REGISTRATION  SYSTEM\\src\\py.jpg");
    this.setIconImage(image.getImage());
    this.setTitle("Corp_Admin_Update");       
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Corp_Admin_Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Corp_Admin_Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Corp_Admin_Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Corp_Admin_Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Corp_Admin_Update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JButton bak;
    private javax.swing.JButton date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mail;
    private javax.swing.JTextField name;
    private javax.swing.JButton rst;
    private javax.swing.JButton src;
    private javax.swing.JTextField view;
    private javax.swing.JTextField word;
    // End of variables declaration//GEN-END:variables
}
