/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.ImageIcon;


/**
 *
 * @author AGAMUYI PRECIOUS
 */
public class Corp_Admin extends javax.swing.JFrame {

    /**
     
     */
    public Corp_Admin() {
        super("Corp_Admin");
        initComponents();
    }
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs =null;
    

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Tpass = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        Tmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        question = new javax.swing.JComboBox<>();
        ans = new javax.swing.JTextField();
        Sub = new javax.swing.JButton();
        Bck = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\AGAMUYI PRECIOUS\\Documents\\NetBeansProjects\\NYSC CORPS_MEMBER REGISTRATION  SYSTEM\\pix.jpg")); // NOI18N
        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel2.setForeground(new java.awt.Color(153, 0, 153));
        jPanel2.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 102));
        jLabel5.setText("UserName:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 40, 80, 20);

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel2.add(name);
        name.setBounds(200, 40, 180, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 102));
        jLabel6.setText("Password:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 100, 63, 15);
        jPanel2.add(Tpass);
        Tpass.setBounds(200, 90, 180, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 102));
        jLabel7.setText("E-Mail:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 150, 40, 15);
        jPanel2.add(Tmail);
        Tmail.setBounds(200, 140, 180, 30);
        jPanel2.add(jLabel2);
        jLabel2.setBounds(390, 140, 0, 0);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 102));
        jLabel3.setText("Security Question:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 190, 120, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 102));
        jLabel4.setText("Answer:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 230, 50, 15);

        question.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please select security question", "What is your fathers name?", "What is your school name?", "What is the name of your mother?", "What is your bestfriend name?" }));
        jPanel2.add(question);
        question.setBounds(200, 182, 180, 30);
        jPanel2.add(ans);
        ans.setBounds(200, 230, 180, 30);

        Sub.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Sub.setForeground(new java.awt.Color(153, 0, 102));
        Sub.setIcon(new javax.swing.ImageIcon("C:\\Users\\AGAMUYI PRECIOUS\\Documents\\NetBeansProjects\\NYSC CORPS_MEMBER REGISTRATION  SYSTEM\\my icons\\Submit Progress_50px.png")); // NOI18N
        Sub.setText("Submit");
        Sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubActionPerformed(evt);
            }
        });
        jPanel2.add(Sub);
        Sub.setBounds(40, 280, 140, 60);

        Bck.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Bck.setForeground(new java.awt.Color(153, 0, 102));
        Bck.setIcon(new javax.swing.ImageIcon("C:\\Users\\AGAMUYI PRECIOUS\\Documents\\NetBeansProjects\\NYSC CORPS_MEMBER REGISTRATION  SYSTEM\\my icons\\Back Arrow_50px.png")); // NOI18N
        Bck.setText("Back");
        Bck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BckActionPerformed(evt);
            }
        });
        jPanel2.add(Bck);
        Bck.setBounds(200, 280, 130, 60);

        Reset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Reset.setForeground(new java.awt.Color(153, 0, 102));
        Reset.setIcon(new javax.swing.ImageIcon("C:\\Users\\AGAMUYI PRECIOUS\\Documents\\NetBeansProjects\\NYSC CORPS_MEMBER REGISTRATION  SYSTEM\\my icons\\Reset_50px.png")); // NOI18N
        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        jPanel2.add(Reset);
        Reset.setBounds(340, 280, 127, 60);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\AGAMUYI PRECIOUS\\Documents\\NetBeansProjects\\NYSC CORPS_MEMBER REGISTRATION  SYSTEM\\pix3.jpg")); // NOI18N
        jPanel2.add(jLabel8);
        jLabel8.setBounds(0, -10, 494, 370);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        name.setText(null);
        Tpass.setText(null);
        Tmail.setText(null);
        ans.setText(null);
    }//GEN-LAST:event_ResetActionPerformed

    private void SubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubActionPerformed
        // TODO add your handling code here:
                                                 if(name.getText().equals("")){
                                                     JOptionPane.showMessageDialog(null, "Please input your details\n                                                              the fields are empty");
                                                 }else{
                      try{
                                                Nysc_Connect.getConnection();
                                                conn= DriverManager.getConnection("jdbc:mysql://localhost/nysc resgistration system","root","");
                                                 String sql ="INSERT INTO admin(user_name,password,e_mail,Sec_Q,Answer)VALUES(?,?,?,?,?)" ; 
                                                pst= conn.prepareStatement(sql);
                                                pst.setString(1,name.getText());
                                                pst.setString(2,Tpass.getText());
                                                pst.setString(3,Tmail. getText());
                                                pst.setString(4,(String)question.getSelectedItem());
                                                pst.setString(5,ans.getText());
                                                
                                                pst.executeUpdate();
                                                
                                                JOptionPane.showMessageDialog(null,"Corp  Admin successfully added");
            
            
 
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(null, e);
        }
                                                 }
    }//GEN-LAST:event_SubActionPerformed

    private void BckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BckActionPerformed
        // TODO add your handling code here:
                                                    setVisible(false);
                                                    Home info = new Home();
                                                    info.setVisible(true); 
                                                     this.dispose();
    }//GEN-LAST:event_BckActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
 ImageIcon image = new ImageIcon("C:\\Users\\AGAMUYI PRECIOUS\\Documents\\NetBeansProjects\\NYSC CORPS_MEMBER REGISTRATION  SYSTEM\\src\\py.jpg");
    this.setIconImage(image.getImage());
    this.setTitle("Corp_Admin");        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Corp_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Corp_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Corp_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Corp_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Corp_Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bck;
    private javax.swing.JButton Reset;
    private javax.swing.JButton Sub;
    private javax.swing.JTextField Tmail;
    private javax.swing.JPasswordField Tpass;
    private javax.swing.JTextField ans;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField name;
    private javax.swing.JComboBox<String> question;
    // End of variables declaration//GEN-END:variables
}
